[workspace]
members = ["crates/core", "crates/manifest", "crates/bank", "crates/audioware"]
resolver = "3"

[workspace.package]
version = "1.9.9"
edition = "2024"
rust-version = "1.97.1"

[profile.release]
codegen-units = 1

[profile.staging]
inherits = "release"
debug = true

[workspace.dependencies]
audioware-core = { path = "crates/core" }
audioware-manifest = { path = "crates/manifest" }
audioware-bank = { path = "crates/bank" }
either = "1.15.0"
glam = "0.33.0"
hotpath = "0.15.0"
humantime = "2.3"
kira = { git = "https://github.com/Roms1383/kira", rev = "10e78eea757d564530c6d04d8d98849650b94862", features = ["serde"] }
rayon = "1.11"
red4ext-rs = { git = "https://github.com/jac3km4/red4ext-rs", rev = "d419d98d8b81a19a62585d11759fabdeabeb0957" }
serde = "1.0"
snafu = "0.9"

[profile.dev.package.kira]
opt-level = 3

[profile.dev.package.cpal]
opt-level = 3

[profile.dev.package.symphonia]
opt-level = 3

[profile.dev.package.symphonia-bundle-mp3]
opt-level = 3

[profile.dev.package.symphonia-format-ogg]
opt-level = 3

[profile.dev.package.symphonia-codec-vorbis]
opt-level = 3

[profile.dev.package.symphonia-bundle-flac]
opt-level = 3

[profile.dev.package.symphonia-codec-pcm]
opt-level = 3
